microk8s:
  children:
    master:
      hosts:
        k8s-master:
          ansible_host: 192.168.1.10
    workers:
      hosts:
        k8s-worker-1:
          ansible_host: 192.168.1.11
        k8s-worker-2:
          ansible_host: 192.168.1.12
  vars:
    # Global variables for all nodes in the cluster
    ansible_user: "temp"
    ansible_password: "temp"
    microk8s_version: "1.32/stable"
